In [5]:
import pandas as pd, numpy as np, random

random.seed(42)
np.random.seed(42)
raw = pd.DataFrame({
    'name': [f'Item_{i}' for i in range(100)],
    'price': [round(random.uniform(5, 100), 2) if random.random() > 0.1 else None for _ in range(100)],
    'qty': [str(random.randint(1, 20)) if random.random() > 0.05 else 'N/A' for _ in range(100)],
    'category': [random.choice(['Electronics','Home','Sports', None]) for _ in range(100)],
})
# Add 5 duplicate rows
raw = pd.concat([raw, raw.head(5)], ignore_index=True)
print(f"Raw data: {len(raw)} rows, nulls: {raw.isnull().sum().sum()}, dupes: {raw.duplicated().sum()}")
raw.head()

Raw data: 105 rows, nulls: 48, dupes: 5

     name  price qty     category
0  Item_0   7.38   8         Home
1  Item_1  26.21  18       Sports
2  Item_2  69.29  14          NaN
3  Item_3  13.26  15  Electronics
4  Item_4   7.83   3       Sports

In [6]:
df = raw.drop_duplicates().copy()

df['price'] = df['price'].fillna(df['price'].median())

df['qty'] = pd.to_numeric(df['qty'], errors='coerce')
df['qty'] = df['qty'].fillna(df['qty'].median())
df['qty'] = df['qty'].astype(int)

df['category'] = df['category'].fillna("Unknown")

df['revenue'] = df['price'] * df['qty']

df.head()

     name  price  qty     category  revenue
0  Item_0   7.38    8         Home    59.04
1  Item_1  26.21   18       Sports   471.78
2  Item_2  69.29   14      Unknown   970.06
3  Item_3  13.26   15  Electronics   198.90
4  Item_4   7.83    3       Sports    23.49

In [7]:
assert len(df) == 100, "Should have 100 rows after dedup"
assert df.isnull().sum().sum() == 0, "No nulls should remain"
assert 'revenue' in df.columns, "Missing revenue column"
assert df['qty'].dtype in ['int64','int32'], "qty should be integer"
print("All checks passed!")

All checks passed!